name: Annotate From file
description: Annotates the build with the contents of a file
author: https://github.com/phcyso
requirements: []
configuration:
  properties:
    path:
      type: string
    style:
      type: string
    must_exist:
      type: boolean
    context:
      type: string
    append:
      type: boolean
  additionalProperties: false
